name: Backend CI

on:
  push:
    paths:
      - "image-proxy/**"
      - ".github/workflows/backend-*.yml"
  pull_request:
    paths:
      - "image-proxy/**"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: image-proxy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: "image-proxy/.nvmrc"
          cache: "npm"
          cache-dependency-path: "image-proxy/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Lint codebase
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Build project
        run: npm run build --if-present
